@url = http://localhost:3000 

###Crear un rectangulo
POST {{url}}/resultado
Content-Type: application/json

{
    "base": 15,
    "altura": 30
}

###Crear un rectangulo
POST {{url}}/resultado
Content-Type: application/json

{
    "base": -15,
    "altura": 20
}

###Modificar un rectángulo 
PUT {{url}}/resultado/3
Content-Type: application/json

{
  "base": 10,
  "altura": 8
}

###Quitar un rectangulo por id
DELETE {{url}}/resultado/1

###Ver rectangulos
GET {{url}}/calculo
